name: downloads_path_provider_28
description: Flutter plugin to get the download directory for Android modified for sdk version 28+. Forked from Daniel MF.
version: 0.1.2
homepage: https://github.com/chitgoks/downloads_path_provider

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: DownloadsPathProviderPlugin
      android:
        package: it.nplace.downloadspathprovider
        pluginClass: DownloadsPathProviderPlugin
